name: Update Daily Quote

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 */4 * * *'  # 每4小时执行一次，可以根据需要调整

env:
  TZ: Asia/Shanghai

permissions:
  contents: read

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get a random quote
        run: |
          RANDOM_OBJECT=$(jq -c '.[]' quotes.json | shuf -n 1)
          QUOTE=$(echo "$RANDOM_OBJECT" | jq -r '.quote')
          AUTHOR=$(echo "$RANDOM_OBJECT" | jq -r '.author')
          echo "QUOTE=$QUOTE" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i.bak "/https:\/\/quotes-github-readme.vercel.app\/api\?/s|quote=[^&]*|quote=${{ env.QUOTE }}|; s|author=[^)]*|author=${{ env.AUTHOR }}|" README.md
          
      - name: Debug variables
        run: |
          echo "QUOTE: $QUOTE"
          echo "AUTHOR: $AUTHOR"

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md README.md.bak
          git commit -m "Update quote and author in README.md" || echo "No changes to commit"
          git remote -v
          git push
